package:
  name: tweepipe
  version: 0.0.1

source:
  git_url: https://github.com/sachalevy/tweepipe.git

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - omegaconf
    - tweepy
    - joblib
    - numpy
    - xgboost
    - regex
    - mongowrapper
    - loguru

test:
  imports:
    - tweepipe

about:
  home: https://github.com/sachalevy/tweepipe
